### ISSUE TITLE
Agent tests

### ISSUE THREAD

**Issue by MarkEdmondson1234** [sunholo-data/sunholo-py#15]
@ellipsis-dev please make a test and put it in the test folder for the utils/config.py file

**Comment by MarkEdmondson1234** [comment]
@ellipsis-dev please adjust to use pytest

**Comment by nsbradford** [comment]
^ infra provider issues last night, fixing...

**Comment by nsbradford** [comment]
> https://github.com/ellipsis-dev please adjust to use pytest

Currently, if you want Ellipsis to modify a PR it made, you have to comment on the PR itself instead of on the issue again (otherwise it will regenerate the PR from scratch) - I see you got that working at https://github.com/sunholo-data/sunholo-py/pull/16

**Comment by MarkEdmondson1234** [comment]
@nsbradford yep worked it out, thanks for the support! I know this is all WIP happy to help test it out
